# Generated by Django 2.2.6 on 2019-10-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeVents', '0002_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
