# Generated by Django 2.2.6 on 2019-10-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeVents', '0005_genero_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes pagina')),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes_Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes pagina')),
            ],
        ),
    ]
