# Generated by Django 2.2.6 on 2019-11-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_imagenes_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes_pagina',
            name='descripcion',
            field=models.TextField(default='1'),
        ),
    ]
