# Generated by Django 2.2.6 on 2019-11-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_imagenes_pagina_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes_pagina',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes pagina'),
        ),
        migrations.AlterField(
            model_name='imagenes_pagina',
            name='descripcion',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='imagenes_pagina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes pagina'),
        ),
    ]
