# Generated by Django 2.2.6 on 2019-11-08 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191103_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('moderador', 'Es moderador'), ('publico', 'Es publico'))},
        ),
    ]
