# Generated by Django 2.2.6 on 2019-11-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20191107_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('moderador', 'Es moderador'), ('usuario', 'Es usuario'))},
        ),
    ]
