# Generated by Django 2.2.6 on 2019-10-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeVents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=200)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
