# Generated by Django 2.2.6 on 2019-10-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeVents', '0003_boleta_producto_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='img'),
        ),
    ]
