# Generated by Django 2.2.6 on 2019-10-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeVents', '0003_auto_20191029_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genero',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img/categorias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='img/productos'),
        ),
    ]
