# Generated by Django 2.2.6 on 2019-10-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeVents', '0006_carousel_imagenes_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Carousel'),
        ),
    ]
