# Generated by Django 2.2.6 on 2019-10-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeVents', '0007_auto_20191030_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
